In [1]:
import os
import pandas as pd

In [5]:
df_toys=pd.read_excel('Toy Building Tracker.xlsx',sheet_name='Toy Building Tracker') #Elf Name Lookup

In [30]:
df_toys.columns[]
# = ['a','b']
#df_toys.iloc[0,:2].values

'Toy Building Tracker'

In [15]:
df_toys

,Toy Building Tracker,Unnamed: 1,Production Manager,Quality Assurance,Fun Levels Tester,Chief Wrapper,Jan,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 47,Unnamed: 48,Unnamed: 49,Nov,Unnamed: 51,Unnamed: 52,Unnamed: 53,Dec,Unnamed: 55,Unnamed: 56
0,Toy,Quota,NaN,NaN,NaN,NaN,2023-01-02 00:00:00,2023-01-09 00:00:00,2023-01-16 00:00:00,2023-01-23 00:00:00,...,2023-10-16 00:00:00,2023-10-23 00:00:00,2023-10-30 00:00:00,2023-11-06 00:00:00,2023-11-13 00:00:00,2023-11-20 00:00:00,2023-11-27 00:00:00,2023-12-04 00:00:00,2023-12-11 00:00:00,2023-12-18 00:00:00
1,Number of Children on the Nicest List,200000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Barbie's Dream House,0.4,JM,VZ,CA,IK,1943894,1836425,2334772,855571,...,374941,1779605,2226173,1293465,115032,1171665,357865,1810119,909812,23637
3,Bike,0.3,RG,JM,LB,EO,206133,909388,1765612,1563600,...,1025566,1134577,1392360,2647668,2764537,97602,1131562,2094502,1773634,2207822
4,Large Lego Set,0.3,SW,CA,HX,TP,2461917,88439,1219444,1445969,...,2692125,1495567,1080902,882922,839257,2319624,544070,120022,1543308,2229822
5,Number of Children on the Nicer than Most List,300000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Barbie Convertible Car,0.25,NU,IK,JM,RG,1913067,523581,838996,564224,...,2293971,2198249,1564893,1383075,1811676,726334,1145636,1728918,1151056,1269416
7,Medium Lego Set,0.25,TP,LB,EO,CA,1371921,1685534,828360,1962565,...,1047218,1985617,419553,2141402,240154,218867,430263,120976,2063577,1952755
8,Scooter,0.25,HX,RG,TP,NU,455631,2280887,1182415,429049,...,424632,2017143,1704998,1442209,1651702,898709,1993307,2126447,847614,2221167
9,Board Game,0.1,VZ,TP,FD,JM,340645,1904473,475800,1735584,...,648218,1800941,1897835,69888,431781,27783,327797,1053347,2208390,575763
10,Squishmallow,0.15,CA,SW,IK,FD,1580166,412187,238533,1453491,...,1319228,1825739,757085,2056863,343115,1110404,1740885,877086,337386,89661
11,Number of Children on the Nice List,500000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Barbie Doll,0.35,IK,FD,RG,HX,3857118,1284332,3150718,2448917,...,4882355,4554232,1894301,1649271,3652921,4460803,1408423,288395,3522015,4237382
13,Small Lego Set,0.2,EO,JM,SW,FD,3071642,1467901,641866,4060128,...,163281,2065865,4248440,1795801,3005639,4219037,2840742,1748852,938609,4363547
14,Skateboard,0.25,FD,EO,CA,LB,2172968,319248,3016465,2372145,...,1663923,1801833,4402694,4291444,1150219,4747979,2102936,1787492,3519083,2826012
15,Teddy Bear,0.2,LB,NU,VZ,TP,4632209,4730777,6707,2128907,...,2674701,1750638,1742067,875247,2711046,1021898,1250357,2074912,133653,3736803