# Preppin data 2021 07 18
## It's Coming Rome
### https://preppindata.blogspot.com/2021/07/2021-week-28-its-coming-rome.html

Challenge by Tom Prowse.

'55 years of hurt, Never stopped me dreaming!'

It was another night of pain for England fans on Sunday evening when they lost yet another penalty shootout in the European Football Championship final. This seems like it has been a common outcome for a lot of the tournaments that England have taken part in over the years, but what does the data agree? 

The challenge this week is to analyse the all of the penalty shootouts in the World Cup and European Championships (Euro's) since 1976.


File locatoin : https://drive.google.com/file/d/1KKaXVz2pqgp7zwLdAbFTHvC_67jYq47H/view?usp=sharing

In [194]:
import os
import pandas as pd
import datetime
import shutil

In [195]:
# frmfolder = r'C:\Users\nprol195\Downloads\InternationalPenalties.xlsx'
# tofolder = os.getcwd()+'\\InternationalPenalties.xlsx'
# shutil.move(frmfolder,tofolder)

In [196]:
dta = pd.read_excel('InternationalPenalties.xlsx', sheet_name=None)

### Determine what competition each penalty was taken in

In [197]:
for i in dta.keys():
    dta[i]['competition'] = i
    dta[i].columns = [clm.lower().strip().replace(' ','_') for clm in dta[i].columns]
 

df = pd.DataFrame()
for i in dta.keys():
    df=df.append(dta[i]).reset_index(drop=True)
    
# df
# df.to_csv('combined.csv')

### Clean any fields, correctly format the date the penalty was taken, & group the two German countries (eg, West Germany & Germany)

In [198]:
# df.info()

In [199]:
df['event_year']=df['event_year'].apply(lambda x: x.replace(',',''))
df['winner']=df['winner'].astype('str')
df['winner']=df['winner'].apply(lambda x : x.replace('\xa0',''))
df['loser']=df['loser'].apply(lambda x : x.replace('\xa0',''))
df['winning_team_taker']=df['winning_team_taker'].astype('str')
df['winning_team_taker']=df['winning_team_taker'].apply(lambda x : x.replace('\xa0','_'))
df['losing_team_taker']=df['losing_team_taker'].astype('str')
df['losing_team_taker']=df['losing_team_taker'].apply(lambda x : x.replace('\xa0','_'))
df.replace(to_replace={'West Germany':'Germany'},inplace=True)

### Rank the countries on the following: 
Shootout win % (exclude teams who have never won a shootout)

Penalties scored %

### Shootout win % (exclude teams who have never won a shootout)

In [200]:
df['winning_team_scores'] =  df['winning_team_taker'].apply(lambda x: 1 if 'scored' in x else 0)
df['losing_team_scores'] =  df['losing_team_taker'].apply(lambda x: 1 if 'scored' in x else 0)

In [201]:
df2 = df[['winner','loser', 'date', 'competition', 'winning_team_scores', 'losing_team_scores']].copy()
df2 = df2.groupby(['winner', 'loser', 'date', 'competition']).sum().reset_index().copy()
df2['no_records'] = 1

In [202]:
win = df2[['winner','no_records']].groupby('winner').sum().reset_index()
win.rename(columns={'no_records':'wins','winner':'team'},inplace=True)
lose = df2[['loser','no_records']].groupby('loser').sum().reset_index()
lose.rename(columns={'no_records':'losses','loser':'team'},inplace=True)

In [203]:
shootouts = win.append(lose).fillna(0) 
shootouts = shootouts.groupby('team').sum()
shootouts['total_games'] = shootouts['wins']+shootouts['losses']
shootouts['pct'] =  round(shootouts['wins']/shootouts['total_games']*100)
shootouts=shootouts[shootouts['wins'] > 0].sort_values(['pct','wins'],ascending=False).reset_index().copy()
shootouts['rank'] = shootouts['pct'].rank(method='dense',ascending=False)
shootouts

                   team  wins  losses  total_games    pct  rank
0        Czechoslovakia   2.0     0.0          2.0  100.0   1.0
1               Belgium   1.0     0.0          1.0  100.0   1.0
2              Bulgaria   1.0     0.0          1.0  100.0   1.0
3        Czech Republic   1.0     0.0          1.0  100.0   1.0
4              Paraguay   1.0     0.0          1.0  100.0   1.0
5           South Korea   1.0     0.0          1.0  100.0   1.0
6                Turkey   1.0     0.0          1.0  100.0   1.0
7               Ukraine   1.0     0.0          1.0  100.0   1.0
8               Uruguay   1.0     0.0          1.0  100.0   1.0
9               Germany   6.0     1.0          7.0   86.0   2.0
10            Argentina   4.0     1.0          5.0   80.0   3.0
11               Brazil   3.0     1.0          4.0   75.0   4.0
12             Portugal   3.0     1.0          4.0   75.0   4.0
13              Croatia   2.0     1.0          3.0   67.0   5.0
14                Spain   5.0     5.0         10.0   50.0   6.0
15           Costa Rica   1.0     1.0          2.0   50.0   6.0
16               Poland   1.0     1.0          2.0   50.0   6.0
17  Republic of Ireland   1.0     1.0          2.0   50.0   6.0
18               Russia   1.0     1.0          2.0   50.0   6.0
19               Sweden   1.0     1.0          2.0   50.0   6.0
20                Italy   5.0     6.0         11.0   45.0   7.0
21               France   3.0     4.0          7.0   43.0   8.0
22              Denmark   1.0     2.0          3.0   33.0   9.0
23          Netherlands   2.0     5.0          7.0   29.0  10.0
24          Switzerland   1.0     3.0          4.0   25.0  11.0
25              England   2.0     7.0          9.0   22.0  12.0

### Penalties scored %

In [204]:
df3 = df.copy()
df3 = df3[df3['winning_team_taker'] != 'nan']
df3['tf']=df3['winning_team_taker'].apply(lambda x: 'scored' in x)
df3['penalties_scored'] = df3['tf'].apply(lambda x: 1 if x else 0)
df3['penalties_missed'] = df3['tf'].apply(lambda x: 1 if not x else 0)
win = df3[['winner','penalties_scored', 'penalties_missed']].copy()
win['total'] = win['penalties_scored']+win['penalties_missed']
win = win.groupby('winner').sum().copy()

In [205]:
df3 = df.copy()
df3 = df3[df3['losing_team_taker'] != 'nan']
df3['tf']=df3['losing_team_taker'].apply(lambda x: 'scored' in x)
df3['penalties_scored'] = df3['tf'].apply(lambda x: 1 if x else 0)
df3['penalties_missed'] = df3['tf'].apply(lambda x: 1 if not x else 0)
lose = df3[['loser','penalties_scored', 'penalties_missed']].copy()
lose['total'] = lose['penalties_scored']+lose['penalties_missed']
lose = lose.groupby('loser').sum().copy()

In [206]:
penalties_pct = win.append(lose).reset_index().groupby('index').sum()
penalties_pct['pct'] = round(penalties_pct['penalties_scored']/penalties_pct['total']*100)
penalties_pct.sort_values(['pct','penalties_scored'],ascending=False)

                     penalties_scored  penalties_missed  total    pct
index
Czechoslovakia                     14                 0     14  100.0
Czech Republic                      6                 0      6  100.0
Belgium                             5                 0      5  100.0
Paraguay                            5                 0      5  100.0
South Korea                         5                 0      5  100.0
Turkey                              3                 0      3  100.0
Poland                              8                 1      9   89.0
Germany                            32                 5     37   86.0
France                             29                 7     36   81.0
Costa Rica                          8                 2     10   80.0
Uruguay                             4                 1      5   80.0
Russia                              7                 2      9   78.0
Argentina                          17                 5     22   77.0
Portugal                           16                 5     21   76.0
Sweden                              9                 3     12   75.0
Bulgaria                            3                 1      4   75.0
Greece                              3                 1      4   75.0
Japan                               3                 1      4   75.0
Ukraine                             3                 1      4   75.0
Denmark                            11                 4     15   73.0
Romania                             8                 3     11   73.0
Brazil                             13                 5     18   72.0
Spain                              33                14     47   70.0
Republic of Ireland                 7                 3     10   70.0
Italy                              42                19     61   69.0
Netherlands                        22                10     32   69.0
England                            29                16     45   64.0
Colombia                            3                 2      5   60.0
Switzerland                        10                 7     17   59.0
Croatia                             8                 6     14   57.0
Ghana                               2                 2      4   50.0
Chile                               2                 3      5   40.0
Yugoslavia                          2                 3      5   40.0
Mexico                              2                 5      7   29.0

### What is the most and least successful time to take a penalty? (What penalty number are you most likely to score or miss?)

In [207]:
df.columns

Index(['no.', 'penalty_number', 'event_year', 'winner', 'full_time_score',
       'loser', 'winning_team_gk', 'winning_team_taker', 'losing_team_taker',
       'losing_team_gk', 'round', 'date', 'competition', 'winning_team_scores',
       'losing_team_scores'],
      dtype='object')

In [208]:
df[['no.', 'penalty_number', 'event_year', 'winner', 'full_time_score',
       'loser', 'winning_team_gk', 'winning_team_taker', 'losing_team_taker',
       'losing_team_gk', 'round', 'date', 'competition', 'winning_team_scores',
       'losing_team_scores']]

,no.,penalty_number,event_year,winner,full_time_score,loser,winning_team_gk,winning_team_taker,losing_team_taker,losing_team_gk,round,date,competition,winning_team_scores,losing_team_scores
0,1,1,1982,Germany,3–3,France,Schumacher,Kaltz_Penalty scored,Penalty scored_Giresse,Ettori,Semi-finals,2021-07-08,WorldCup,1,1
1,1,2,1982,Germany,3–3,France,Schumacher,Breitner_Penalty scored,Penalty scored_Amoros,Ettori,Semi-finals,2021-07-08,WorldCup,1,1
2,1,3,1982,Germany,3–3,France,Schumacher,Stielike_Penalty missed,Penalty scored_Rocheteau,Ettori,Semi-finals,2021-07-08,WorldCup,0,1
3,1,4,1982,Germany,3–3,France,Schumacher,Littbarski_Penalty scored,Penalty missed_Six,Ettori,Semi-finals,2021-07-08,WorldCup,1,0
4,1,5,1982,Germany,3–3,France,Schumacher,Rummenigge_Penalty scored,Penalty scored_Platini,Ettori,Semi-finals,2021-07-08,WorldCup,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,22,1,2020,Italy,1–1,England,Donnarumma,Berardi_Penalty scored,Penalty scored_Kane,Pickford,Final,2021-07-11,Euros,1,1
262,22,2,2020,Italy,1–1,England,Donnarumma,Belotti_Penalty missed,Penalty scored_Maguire,Pickford,Final,2021-07-11,Euros,0,1
263,22,3,2020,Italy,1–1,England,Donnarumma,Bonucci_Penalty scored,Penalty missed_Rashford,Pickford,Final,2021-07-11,Euros,1,0
264,22,4,2020,Italy,1–1,England,Donnarumma,Bernardeschi_Penalty scored,Penalty missed_Sancho,Pickford,Final,2021-07-11,Euros,1,0
265,22,5,2020,Italy,1–1,England,Donnarumma,Jorginho_Penalty missed,Penalty missed_Saka,Pickford,Final,2021-07-11,Euros,0,0

In [209]:
windf=df[['penalty_number', 'winner', 'winning_team_taker', 'winning_team_scores']].copy()

In [210]:
losedf = df[[ 'penalty_number','loser', 'losing_team_taker', 'losing_team_scores']].copy()

In [211]:
for i in [windf,losedf]:
    i.columns = [ 'penalty_number','team', 'team_taker', 'score']
teamdf = windf.append(losedf)
teamdf['misses']=teamdf['score'].apply(lambda x: 1 if x == 0 else 0)    
teamdf = teamdf.groupby(['penalty_number']).sum().copy()

In [212]:
teamdf['total'] = teamdf['score']+teamdf['misses']
teamdf['pct'] = round(teamdf['score']/teamdf['total']*100)
teamdf['rank'] = teamdf['pct'].rank(method='dense',ascending=False)
teamdf.sort_values('pct',ascending=False)

                score  misses  total    pct  rank
penalty_number
8                   4       0      4  100.0   1.0
7                   5       1      6   83.0   2.0
1                  80      24    104   77.0   3.0
3                  80      24    104   77.0   3.0
2                  79      25    104   76.0   4.0
6                  11       5     16   69.0   5.0
4                  64      40    104   62.0   6.0
5                  49      37     86   57.0   7.0
9                   2       2      4   50.0   8.0