In [261]:
import os
import pandas as pd
import datetime as dt
import numpy as np

In [262]:
df = pd.read_excel('PD 2021 Wk 18 Input.xlsx')

In [263]:
df.head()

,Project,Sub-project,Task,Owner,Scheduled Date,Completed In Days from Scheduled Date
0,New Loyalty Scheme,Marketing,Scope,Tom,2021-04-19,0
1,New Loyalty Scheme,Marketing,Build,Tom,2021-04-21,2
2,New Loyalty Scheme,Marketing,Deliver,Tom,2021-04-30,5
3,New Loyalty Scheme,Operations,Scope,Jenny,2021-04-15,0
4,New Loyalty Scheme,Operations,Build,Jenny,2021-04-23,3

In [264]:
df.columns = [x.lower().strip().replace(' ','_') for x in df.columns]

In [265]:
temp = df['completed_in_days_from_scheduled_date'].apply(lambda x: pd.Timedelta(x, unit='D'))
temp

0    0 days
1    2 days
2    5 days
3    0 days
4    3 days
5    4 days
6    0 days
7    6 days
8    3 days
9    0 days
10   2 days
11   4 days
12   0 days
13   3 days
14   5 days
15   0 days
16   2 days
17   6 days
Name: completed_in_days_from_scheduled_date, dtype: timedelta64[ns]

In [266]:
df['completed_date'] = df['scheduled_date'] + temp

In [267]:
df = df.rename(columns={'completed_in_days_from_scheduled_date':'days_difference_to_schedule'}).copy()

In [268]:
df2 = df[['project', 'sub-project', 'task', 'owner', 'completed_date']].set_index(['project', 'sub-project', 'owner','task']).unstack().reset_index().copy()

In [269]:
df2

                    project sub-project     owner completed_date             \
task                                                       Build    Deliver
0        New Loyalty Scheme   Marketing       Tom     2021-04-23 2021-05-05
1        New Loyalty Scheme  Operations     Jenny     2021-04-26 2021-05-02
2     New Trolley Inventory   Marketing       Tom     2021-05-07 2021-05-17
3     New Trolley Inventory  Operations     Jenny     2021-05-07 2021-05-17
4               Spring Sale   Marketing      Carl     2021-05-05 2021-05-07
5               Spring Sale  Operations  Jonathan     2021-04-30 2021-05-06


task      Scope
0    2021-04-19
1    2021-04-15
2    2021-05-02
3    2021-04-30
4    2021-04-22
5    2021-04-25

In [270]:
df2['scope_to_build'] = df2['completed_date']['Build']-df2['completed_date']['Scope']
df2['build_to_delivery'] = df2['completed_date']['Deliver']-df2['completed_date']['Build']

In [271]:
df2final = df2.set_index(['project','sub-project','owner','scope_to_build','build_to_delivery']).stack().copy()

In [272]:
df2final = df2final.reset_index()

In [278]:
mergeddf = df.merge(df2final,how='outer',on=['project', 'sub-project', 'owner','task','completed_date'])

In [279]:
mergeddf['weekday'] = mergeddf['completed_date'].apply(lambda x:x.date().strftime('%A'))

In [280]:
mergeddf[['weekday','task','build_to_delivery','scope_to_build',
          'days_difference_to_schedule','project',
          'sub-project','owner','scheduled_date','completed_date']].set_index('weekday')

,task,build_to_delivery,scope_to_build,days_difference_to_schedule,project,sub-project,owner,scheduled_date,completed_date
weekday,,,,,,,,,
Monday,Scope,12 days,4 days,0,New Loyalty Scheme,Marketing,Tom,2021-04-19,2021-04-19
Friday,Build,12 days,4 days,2,New Loyalty Scheme,Marketing,Tom,2021-04-21,2021-04-23
Wednesday,Deliver,12 days,4 days,5,New Loyalty Scheme,Marketing,Tom,2021-04-30,2021-05-05
Thursday,Scope,6 days,11 days,0,New Loyalty Scheme,Operations,Jenny,2021-04-15,2021-04-15
Monday,Build,6 days,11 days,3,New Loyalty Scheme,Operations,Jenny,2021-04-23,2021-04-26
Sunday,Deliver,6 days,11 days,4,New Loyalty Scheme,Operations,Jenny,2021-04-28,2021-05-02
Thursday,Scope,2 days,13 days,0,Spring Sale,Marketing,Carl,2021-04-22,2021-04-22
Wednesday,Build,2 days,13 days,6,Spring Sale,Marketing,Carl,2021-04-29,2021-05-05
Friday,Deliver,2 days,13 days,3,Spring Sale,Marketing,Carl,2021-05-04,2021-05-07
Sunday,Scope,6 days,5 days,0,Spring Sale,Operations,Jonathan,2021-04-25,2021-04-25
Friday,Build,6 days,5 days,2,Spring Sale,Operations,Jonathan,2021-04-28,2021-04-30
Thursday,Deliver,6 days,5 days,4,Spring Sale,Operations,Jonathan,2021-05-02,2021-05-06
Sunday,Scope,10 days,5 days,0,New Trolley Inventory,Marketing,Tom,2021-05-02,2021-05-02
Friday,Build,10 days,5 days,3,New Trolley Inventory,Marketing,Tom,2021-05-04,2021-05-07
Monday,Deliver,10 days,5 days,5,New Trolley Inventory,Marketing,Tom,2021-05-12,2021-05-17
Friday,Scope,10 days,7 days,0,New Trolley Inventory,Operations,Jenny,2021-04-30,2021-04-30
Friday,Build,10 days,7 days,2,New Trolley Inventory,Operations,Jenny,2021-05-05,2021-05-07
Monday,Deliver,10 days,7 days,6,New Trolley Inventory,Operations,Jenny,2021-05-11,2021-05-17